server:
  port: 8080

spring:
  application:
    name: provider-server-customer-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npms?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&useUnicode=true&allowMultiQueries=true
    username: root
    password: 635489
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
   # password: YangYouCai4YangYi!


mybatis-plus:
  mapper-locations: classpath:com/neu/customermanagement/management/mapper/*.xml
  type-aliases-package: com.neu.customermanagement.management.entity, com.neu.customermanagement.management.dto


logging:
  level:
    com.neu.customermanagement: debug


eureka:
  instance:
    #Use the ip address to register with Eureka
    prefer-ip-address: true
  #The above configuration can already be registered with ip, but the host name is still displayed, so set the registered name displayed here    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:13000/eureka/, http://127.0.0.1:13001/eureka/, http://127.0.0.1:13002/eureka/

